"use client";
import {useState,type FormEvent} from 'react';
import {useWorkspace} from './WorkspaceProvider';
import DataTools from './DataTools';
export default function AccountPage({registrationEnabled=false}:{registrationEnabled?:boolean}){
 const {user,ready,online,status}=useWorkspace(),[signup,setSignup]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/auth/'+(signup?'sign-up/email':'sign-in/email'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.trim(),password,...(signup?{name:name.trim()}:{}),rememberMe:true})});const value=await response.json() as {message?:string;error?:string};if(!response.ok)throw Error(value.message||value.error||'Sign-in failed.');const next=new URLSearchParams(location.search).get('return');location.assign(next?.startsWith('/')&&!next.startsWith('//')?next:'/explore-app/planner/trips');}catch(e){setError(e instanceof Error?e.message:'Account service unavailable.');}finally{setBusy(false);}}
 return <><p className="hut-kicker">Private planning, wherever you go</p><h1>{user?'Your account':'Take your plans with you'}</h1><p className="hut-lead">The hut library is public. An account saves your shortlist, trips and documentary plans across devices. A guest workspace stays in this browser until you explicitly import it.</p>{!ready&&<p>Checking your session…</p>}{ready&&user?<section className="hut-panel hut-account"><h2>{user.name}</h2><p>{user.email}</p><p>{status}</p><a className="hut-button" href="/explore-app/planner/trips">Open my hut trips</a><DataTools/><p className="hut-muted">Signing out clears the cached account copy on this device after pending changes are saved. You can export a private backup before signing out.</p></section>:ready&&<section className="hut-panel hut-account"><h2>{signup?'Create an account':'Sign in'}</h2><form onSubmit={submit} className="hut-form" style={{gridTemplateColumns:'1fr'}}>{signup&&<label>Your name<input autoComplete="name" required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label>}<label>Email<input type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={signup?'new-password':'current-password'} required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>{signup&&<p className="hut-muted">Use at least 12 characters. Keep the password in your password manager. Email verification and password recovery are not enabled yet.</p>}<button disabled={busy||!online}>{busy?'Checking…':signup?'Create account':'Sign in'}</button></form>{error&&<p role="alert" className="hut-alert">{error}</p>}{registrationEnabled?<button className="secondary" onClick={()=>{setSignup(s=>!s);setError('');}}>{signup?'I already have an account':'Create an account instead'}</button>:<p className="hut-muted">New account registration is not available on this deployment yet. You can browse the library and save a guest plan on this device. Export/import transfers guest plans between devices.</p>}<p><a href="/huts">Continue browsing as a guest</a></p><DataTools/></section>}</>;
}
