"use client";
import {useState,useRef} from 'react';
import {importGuide} from '@/lib/huts/workspace';
import {useWorkspace} from './WorkspaceProvider';
type Preview=ReturnType<typeof importGuide>;
export function downloadJSON(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function DataTools(){
 const incoming=useRef<unknown>(null);
 const {workspace,change,user}=useWorkspace(),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function file(file?:File){setError('');setMessage('');setPreview(null);if(!file)return;if(file.size>4*1024*1024){setError('Choose an export smaller than 4 MiB.');return;}try{incoming.current=JSON.parse(await file.text());setPreview(importGuide(workspace,incoming.current));}catch(e){setError(e instanceof Error?e.message:'Invalid export.');}}
 function guest(){try{const data=JSON.parse(localStorage.getItem('vm.huts.guest.v1')||'null');if(!data)throw Error('No guest workspace exists on this device.');incoming.current={format:'vertical-moment-hut-workspace',version:1,workspace:data.workspace};setPreview(importGuide(workspace,incoming.current));setError('');}catch(e){setError(e instanceof Error?e.message:'No guest data.');}}
 return <details className="hut-no-print"><summary>Import and export my data</summary><p>Import the existing offline guide’s bookmark or documentary-plan JSON export, or a Vertical Moment workspace export. Existing notes are retained when values conflict.</p><label>Choose an export JSON file<input type="file" accept="application/json,.json" onChange={e=>void file(e.target.files?.[0])}/></label><div className="hut-actions"><button className="secondary" onClick={()=>downloadJSON({format:'vertical-moment-hut-workspace',version:1,exported_at:new Date().toISOString(),workspace},'Vertical_Moment_Private_Workspace_'+new Date().toISOString().slice(0,10)+'.json')}>Export my workspace</button>{user&&<button className="secondary" onClick={guest}>Preview guest data import</button>}</div><p className="hut-muted">The export contains your private notes and permission records. Store and share it with care. This does not export your password or session.</p>{error&&<p className="hut-alert" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{preview&&<section className="hut-private"><h3>Import preview</h3><p>{preview.added} new values · {preview.conflicts.length} retained conflicts · {preview.skipped.length} invalid or unknown values skipped.</p>{preview.conflicts.length>0&&<><p>These existing values will be retained. The incoming values remain in your original export file for review.</p><ul>{preview.conflicts.map(p=><li key={p}>{p}</li>)}</ul></>}{preview.skipped.length>0&&<details><summary>Skipped values</summary><p>{preview.skipped.join(', ')}</p></details>}<button onClick={()=>{change(w=>Object.assign(w,importGuide(w,incoming.current).workspace));setMessage('Reviewed additions applied. Existing conflicting values retained.');setPreview(null);}}>Apply reviewed additions</button><button className="secondary" onClick={()=>setPreview(null)}>Cancel</button></section>}</details>;
}
