"use client";
import {useEffect,useMemo,useState} from 'react';
import {type HutIndex} from '@/lib/huts/types';
import {useWorkspace} from './WorkspaceProvider';
import {useResearch} from './research';
const normal=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const initial={q:'',region:'',range:'',service:'',min:'',max:'',notice:false,history:false,prices:false,diet:false,anniversary:false,saved:false,ids:''};
export default function HutLibrary(){
 const {data,error}=useResearch<HutIndex[]>('/huts-data/v1/index.json'),{workspace,change}=useWorkspace();
 const [filters,setFilters]=useState(initial),[page,setPage]=useState(1),[initialized,setInitialized]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const p=new URLSearchParams(location.search);const f={...initial};for(const key of Object.keys(f)){if(typeof (f as any)[key]==='boolean')(f as any)[key]=p.get(key)==='1';else (f as any)[key]=p.get(key)||'';}setFilters(f);setInitialized(true);const legacy=new URLSearchParams(location.hash.slice(1));const id=legacy.get('hut');if(id&&/^[a-zA-Z0-9-]+$/.test(id))location.replace('/huts/'+encodeURIComponent(id)+(legacy.get('section')?'#section='+encodeURIComponent(legacy.get('section')!):''));},[]);
 useEffect(()=>{setPage(1);if(!initialized)return;const p=new URLSearchParams();for(const [k,v]of Object.entries(filters))if(v)p.set(k,typeof v==='boolean'?'1':v);history.replaceState(null,'','/huts'+(p.size?'?'+p:''));},[filters,initialized]);
 const options=(key:keyof HutIndex)=>[...new Set((data||[]).map(h=>String(h[key]||'')))].filter(Boolean).sort();
 const visible=useMemo(()=>{const q=normal(filters.q),chosen=new Set(filters.ids.split(',').filter(Boolean));return (data||[]).filter(h=>(!q||normal([h.name,h.region,h.mountain_group,h.id,String(h.number),h.story].join(' ')).includes(q))&&(!filters.region||h.region===filters.region)&&(!filters.range||h.mountain_group===filters.range)&&(!filters.service||h.service===filters.service)&&(!filters.min||h.elevation_m!==null&&h.elevation_m>=Number(filters.min))&&(!filters.max||h.elevation_m!==null&&h.elevation_m<=Number(filters.max))&&(!filters.notice||h.has_notice)&&(!filters.history||h.opening_year!==null)&&(!filters.prices||h.has_prices)&&(!filters.diet||h.has_diet)&&(!filters.anniversary||!h.anniversary_hooks.startsWith('No qualified'))&&(!filters.saved||workspace.bookmarks.includes(h.id))&&(!chosen.size||chosen.has(h.id)));},[data,filters,workspace.bookmarks]);
 async function share(selection=false){const u=new URL(location.href);if(selection){u.search='';u.searchParams.set('ids',workspace.bookmarks.join(','));}try{await navigator.clipboard.writeText(u.href);setMessage(selection?'Public hut selection link copied. It contains hut IDs only.':'Library filter link copied.');}catch{setMessage(u.href);}}
 function set(k:string,v:string|boolean){setFilters(f=>({...f,[k]:v}));}
 return <><p className="hut-kicker">The Alpenverein photography master · Vienna as a starting point</p><h1>630 huts. Stories worth walking for.</h1><p className="hut-lead">Browse reviewed hut stories, published approaches and visitor information. Save a shortlist, plan a shoot day, and keep private notes in your own workspace.</p><div className="hut-toolbar"><a className="hut-button" href="/explore-app/planner/trips">Open my hut trips</a><button className="secondary" onClick={()=>void share()}>Share these filters</button><button className="secondary" disabled={!workspace.bookmarks.length} onClick={()=>void share(true)}>Share saved hut selection</button><button className="secondary" onClick={()=>setFilters(initial)}>Clear filters</button></div><p role="status">{message}</p>
 <div className="hut-filters"><label className="hut-search">Find a hut, original list number, ID or story<input type="search" placeholder="Otto-Haus, Rax, 432 or 167" value={filters.q} onChange={e=>set('q',e.target.value)}/></label><label>Region<select aria-label="Region" value={filters.region} onChange={e=>set('region',e.target.value)}><option value="">All regions</option>{options('region').map(v=><option key={v}>{v}</option>)}</select></label><label>Mountain range<select aria-label="Mountain range" value={filters.range} onChange={e=>set('range',e.target.value)}><option value="">All ranges</option>{options('mountain_group').map(v=><option key={v}>{v}</option>)}</select></label><label>Service<select aria-label="Service" value={filters.service} onChange={e=>set('service',e.target.value)}><option value="">All service types</option>{options('service').map(v=><option key={v}>{v}</option>)}</select></label><label>Minimum elevation (m)<input type="number" min="0" value={filters.min} onChange={e=>set('min',e.target.value)}/></label><label>Maximum elevation (m)<input type="number" min="0" value={filters.max} onChange={e=>set('max',e.target.value)}/></label><div className="hut-checks">{[['notice','Operating / access notice'],['history','Original opening recorded'],['prices','Published numeric tariffs'],['diet','Dietary information recorded'],['anniversary','2026–2030 anniversary candidate'],['saved','My saved huts']].map(([key,label])=><label key={key}><input type="checkbox" checked={Boolean((filters as any)[key])} onChange={e=>set(key,e.target.checked)}/>{label}</label>)}</div></div>
 {error&&<p className="hut-alert" role="alert">{error}</p>}{!data&&!error&&<p>Loading the reviewed library…</p>}{data&&<><p className="hut-meta">{visible.length} of 630 huts · List numbers and directory IDs retained · Page {page} of {Math.max(1,Math.ceil(visible.length/24))}</p><div className="hut-grid">{visible.slice((page-1)*24,page*24).map(h=><article className="hut-card" key={h.id}><p className="hut-kicker">No. {h.number} · ID {h.id}</p><h2><a href={'/huts/'+h.id}>{h.name}</a></h2><p className="hut-meta">{h.region} · {h.mountain_group} · {h.elevation_m??'Elevation unconfirmed'} m</p><p>{h.story}</p><p><span className="hut-tag">{h.service}</span>{h.opening_year!==null&&<span className="hut-tag">Original opening {h.opening_year}</span>}</p>{h.has_notice&&<p className="hut-notice"><strong>Before you go</strong><br/>{h.notice_summary}</p>}<div className="hut-actions"><a href={'/huts/'+h.id}>Hut details →</a><button className="hut-small" aria-pressed={workspace.bookmarks.includes(h.id)} onClick={()=>change(w=>{w.bookmarks=w.bookmarks.includes(h.id)?w.bookmarks.filter(id=>id!==h.id):[...w.bookmarks,h.id];})}>{workspace.bookmarks.includes(h.id)?'Saved ✓':'Save hut'}</button></div></article>)}</div>{!visible.length&&<p className="hut-empty">No huts match these filters. Try clearing one filter.</p>}<div className="hut-actions"><button className="secondary" disabled={page<=1} onClick={()=>{setPage(p=>p-1);window.scrollTo({top:0,behavior:'smooth'});}}>Previous page</button><button disabled={page*24>=visible.length} onClick={()=>{setPage(p=>p+1);window.scrollTo({top:0,behavior:'smooth'});}}>Next page</button></div></>}</>;
}
