"use client";
import {useEffect,useState} from 'react';
import {text,safeUrl,type HutDetail,type ResearchRow,type Trip} from '@/lib/huts/types';
import {useWorkspace} from './WorkspaceProvider';
import {useResearch,Facts,RefLinks,FullRecord,OutLink,SourceRow,RouteRow} from './research';
import ShootPlan from './ShootPlan';
const sections=[['overview','Before you go'],['access','Access & parking'],['stay','Stay & rules'],['food','Food & tariffs'],['routes','Routes & mountains'],['history','Hut & regional story'],['events','Events'],['sources','Contacts & sources'],['documentary','My shoot plan']];
const blank=(v:unknown)=>v===null||v===undefined||v===''?'Not established in checked sources':v;
export default function HutPage({id}:{id:string}){
 const {data,error}=useResearch<HutDetail>('/huts-data/v1/'+encodeURIComponent(id)+'.json'),{workspace,change}=useWorkspace(),[message,setMessage]=useState(''),[pick,setPick]=useState(''),[showTrips,setShowTrips]=useState(false);
 useEffect(()=>{if(!data)return;const section=new URLSearchParams(location.hash.slice(1)).get('section');if(section){setTimeout(()=>document.getElementById(section)?.scrollIntoView(),100);}},[data]);
 if(error)return <p role="alert" className="hut-alert">{error}</p>;if(!data)return <p>Loading the reviewed hut record…</p>;
 const h=data.record,v=data.visitor||{},sources=data.sources;
 const groups=Object.groupBy(data.tariffs,t=>String(t.kind||'Other published tariff'));
 const notices=Array.isArray(h.notices)?h.notices as ResearchRow[]:[];
 async function offline(){setMessage('Saving this hut for offline use…');try{if(!('serviceWorker'in navigator)||!navigator.serviceWorker.controller)throw Error('Offline saving is available in the built preview or live site once its service worker is active.');await new Promise<void>((resolve,reject)=>{const channel=new MessageChannel();const timer=setTimeout(()=>reject(Error('The offline download timed out. Try again.')),25000);channel.port1.onmessage=e=>{clearTimeout(timer);e.data.ok?resolve():reject(Error('The offline copy could not be confirmed. Try again.'));};navigator.serviceWorker.controller!.postMessage({type:'SAVE_HUT',id},[channel.port2]);});setMessage('Hut page and checked research saved on this device. Offline notices may age; check current conditions before travelling.');}catch(e){setMessage(e instanceof Error?e.message:'Offline saving failed.');}}
 function addTrip(){const existing=workspace.trips.find(t=>t.id===pick);const name='Visit '+h.name;let tid=existing?.id||crypto.randomUUID();change(w=>{let t=w.trips.find(t=>t.id===tid);if(!t){t={id:tid,name,date:'',destinations:[],notes:'',checklist:{},shoot_status:'Not logged',day_notes:''};w.trips.push(t);}if(!t.destinations.some(d=>d.hut_id===id))t.destinations.push({hut_id:id,approach_id:''});});setShowTrips(false);setMessage('Added to '+(existing?.name||name)+'. Choose the date and published approach in My hut trips.');}
 return <><p className="hut-kicker"><a href="/huts">All 630 huts</a> · Original list No. {h.number} · Directory ID {h.id}</p><h1>{h.name}</h1><p className="hut-lead">{text(h.hut_story)}</p><p className="hut-meta">{text(h.story_status)} · Checked {text(h.story_checked||h.checked)} · <RefLinks value={h.story_refs} sources={sources}/></p><Facts items={[['Region',h.base?.region||h.region],['Mountain range',h.base?.mountain_group||h.mountain_group],['Elevation',h.base?.elevation_m!==undefined&&h.base.elevation_m!==null?String(h.base.elevation_m)+' m':h.elevation_m]]}/>
 <div className="hut-actions"><button aria-pressed={workspace.bookmarks.includes(id)} onClick={()=>change(w=>{w.bookmarks=w.bookmarks.includes(id)?w.bookmarks.filter(x=>x!==id):[...w.bookmarks,id];})}>{workspace.bookmarks.includes(id)?'Saved hut ✓':'Save hut'}</button><button className="secondary" onClick={()=>setShowTrips(x=>!x)}>Add to a trip</button><button className="secondary" onClick={()=>void offline()}>Save for offline</button><button className="secondary" onClick={()=>window.print()}>Print hut guide</button><button className="secondary" onClick={()=>void navigator.clipboard.writeText(location.origin+'/huts/'+id+location.hash).then(()=>setMessage('Hut address copied. Your personal notes are not included.')).catch(()=>setMessage(location.href))}>Copy hut link</button></div><p role="status">{message}</p>{showTrips&&<section className="hut-private hut-no-print"><label>Choose a trip<select aria-label="Choose a trip" value={pick} onChange={e=>setPick(e.target.value)}><option value="">Create a new hut trip</option>{workspace.trips.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button onClick={addTrip}>Add this hut</button></section>}
 <nav className="hut-subnav" aria-label="Hut sections">{sections.map(([key,label])=><a key={key} href={'#section='+key} onClick={()=>setTimeout(()=>document.getElementById(key)?.scrollIntoView(),0)}>{label}</a>)}</nav>
 <section id="overview" className="hut-section"><h2>Before you go</h2>{notices.map((n,i)=><aside key={i} className="hut-notice"><h3>{text(n.title)}</h3><p className="hut-prose">{text(n.text)}</p><p className="hut-meta">Checked {text(n.checked)} · <RefLinks value={n.refs||n.ref} sources={sources}/></p></aside>)}{!notices.length&&<p className={String(h.review_flags).startsWith('No specific')?'hut-muted':'hut-notice'}>{text(h.notice_summary||h.review_flags)} · Checked {text(h.notice_checked||h.checked)}</p>}<Facts items={[['Service',h.status],['Summer operation',h.summer],['Winter operation',h.winter],['Published approach',h.approach_details||h.approach_summary],['Parking',h.parking],['Booking',h.booking||'Booking portal not established; contact operator']]}/><p className="hut-prose">{text(h.notes)}</p><p className="hut-muted">Published plans and notices are dated evidence. Confirm current conditions and any reservation with the operator.</p></section>
 <section id="access" className="hut-section"><h2>Access and parking</h2><Facts items={[['Rail connection',h.rail],['Bus stop / connection',h.bus],['Valley car access',h.car],['Parking conditions',h.parking],['Approach details',h.approach_details],['Access restrictions',h.review_flags]]}/><p>Plan travel from Vienna to the published valley starting point. Hut coordinates show the hut’s location; they do not establish drivable access or an overnight parking permission.</p>{safeUrl(h.website)&&<OutLink url={h.website}>Check official access and current notices</OutLink>}<h3>Published approaches</h3>{data.routes.filter(r=>r.kind==='Approach').map((r,i)=><RouteRow key={i} row={r} sources={sources}/>)}{!data.routes.some(r=>r.kind==='Approach')&&<p>Approach details not established in checked sources.</p>}</section>
 <section id="stay" className="hut-section"><h2>Sleeping places and visitor rules</h2><Facts items={[['Room places',h.room_beds],['Dormitory places',h.dorm_beds],['Winter-room places',h.winter_beds],['Emergency places',h.emergency_beds],['Winter-room access',h.winter_room],['Winter-room key',h.winter_key],['Winter restrictions / shelter',h.winter_notes||h.shelter],['Payment',h.payment],['Sleeping-bag / liner rules',h.liner],['Dogs',h.dogs],['Drinking water',h.water],['Showers',h.showers]]}/><p className="hut-muted">{text(v.capacity_note)} These categories are not added into a guaranteed capacity. Published zero remains zero.</p><p className="hut-prose">{text(v.rules)}</p><FullRecord row={v} label="All reviewed visitor information"/></section>
 <section id="food" className="hut-section"><h2>Food, dietary options and tariffs</h2><Facts items={[['Service',v.service],['Meals',v.meals],['Dietary options',v.diet],['Named dishes',v.dishes]]}/><p className="hut-muted">Dietary availability may depend on advance notice and current service. Ask the operator about the meal and any allergy.</p>{Object.entries(groups).map(([group,rows])=><div className="hut-panel" key={group}><h3>{group}</h3>{rows?.map(t=><article className="hut-row" key={String(t.tariff_id)}><h3>{text(t.category)} · {t.amount===null?'Price not established':text(t.amount)+' '+text(t.currency)}</h3><Facts items={[['Membership / eligibility',t.membership],['Unit',t.unit],['Tariff year',blank(t.tariff_year)],['Validity',t.validity],['Conditions and inclusions',blank(t.conditions)]]}/><p className="hut-meta">{text(t.evidence_type)} · Checked {text(t.checked)} · <RefLinks value={t.ref} sources={sources}/></p><OutLink url={t.source_url}>Published tariff source</OutLink></article>)}</div>)}{!data.tariffs.length&&<p>Numeric tariffs not established in checked sources. Contact the operator for the current price.</p>}<p className="hut-muted">Compare year, age category, membership, unit and inclusions. Old tariff years remain labelled; do not treat them as current quotations.</p></section>
 <section id="routes" className="hut-section"><h2>Surrounding mountains and trails</h2><Facts items={[['Published activities',h.activities],['Summit references',h.summit_summary],['Neighbour huts',h.neighbour_summary],['Protected-area directory note',h.protected]]}/><p className="hut-muted">Directory route references are published descriptions. No straight-line distance is presented as a walking route or journey time.</p>{data.routes.filter(r=>r.kind!=='Approach').map((r,i)=><RouteRow key={i} row={r} sources={sources}/>)}<FullRecord row={data.surroundings||{}} label="Regional relationship record"/></section>
 <section id="history" className="hut-section"><h2>The hut and its region</h2><p className="hut-prose">{text(h.history)}</p><Facts items={[['Original opening / inauguration',blank(h.opening_year)],['Construction / origin',h.construction_origin_summary],['Original-opening qualification',h.opening_note],['Anniversary candidates, 2026–2030',h.anniversary_hooks]]}/><p className="hut-muted">Anniversary candidates are story hooks. They do not establish an announced celebration. Original opening, construction, rebuilding and later milestones remain separate.</p>{data.dates.map(d=><article key={String(d.date_id)} className="hut-row"><h3>{text(d.kind)} · {text(d.exact_date||d.year)}{d.year_end?'–'+d.year_end:''}</h3><p>{text(d.qualification)}</p><p className="hut-meta">{text(d.confidence)} · {text(d.evidence_use)} · Checked {text(d.checked)} · <RefLinks value={d.ref} sources={sources}/></p><p className="hut-meta">{text(d.anniversary_summary)}</p><OutLink url={d.source_url}>Date evidence</OutLink></article>)}{data.contexts.map(c=><article key={String(c.context_id)} className="hut-row"><h3>{text(c.place)} · {text(c.kind)}</h3><p className="hut-prose">{text(c.summary)}</p><p className="hut-meta">{text(c.source_kind)} · Checked {text(c.checked)} · Context {text(c.context_id)} · <RefLinks value={c.ref} sources={sources}/></p><OutLink url={c.source_url}>Regional source</OutLink></article>)}{Boolean(h.wikipedia_url)&&<p><OutLink url={h.wikipedia_url}>Hut-specific Wikipedia page</OutLink> · <RefLinks value={h.wikipedia_ref} sources={sources}/> · Secondary source checked {text(h.source_link_checked)}</p>}<p className="hut-muted">Unresolved research: {text(h.new_gaps||h.gaps)}</p></section>
 <section id="events" className="hut-section"><h2>Events and dated references</h2>{data.events.length?data.events.map(e=><article className="hut-row" key={String(e.event_id)}><h3>{text(e.event)}</h3><Facts items={[['Start',blank(e.start)],['End',blank(e.end)],['Published timing',e.timing],['Status',e.status],['Place',e.location]]}/><p className="hut-prose">{text(e.note)}</p><p className="hut-meta">Checked {text(e.checked)} · <RefLinks value={e.ref} sources={sources}/></p><OutLink url={e.source_url}>Event source</OutLink></article>):<p>Dated events not established in checked sources.</p>}<p className="hut-muted">Respect memorials and private gatherings. Confirm timing and filming consent with organisers before planning a film.</p></section>
 <section id="sources" className="hut-section"><h2>Official contacts and checked sources</h2><Facts items={[['Owner / owning section',h.owner],['Operator',h.operator],['Warden',h.warden],['Phone',h.phone],['Email',h.email],['Address',h.address]]}/><div className="hut-actions"><OutLink url={h.website}>Official hut / operator website</OutLink><OutLink url={h.owner_website}>Owning section</OutLink><OutLink url={h.base?.directory_link||h.directory}>Directory entry</OutLink></div>{sources.map(s=><SourceRow key={String(s.ref)} source={s}/>)}<a href={'/huts/sources?q='+encodeURIComponent(id)}>Browse source records</a><FullRecord row={h} label="Full reviewed hut record"/></section>
 <section id="documentary" className="hut-section"><h2>Photography and filming</h2><ShootPlan detail={data}/></section></>;
}
