"use client";
import {useMemo,useState} from 'react';
import {type HutIndex} from '@/lib/huts/types';
import {useResearch} from './research';
import {useWorkspace} from './WorkspaceProvider';
import DataTools from './DataTools';
export default function LifeList(){
 const {workspace,change,user,ready}=useWorkspace(),{data,error}=useResearch<HutIndex[]>('/huts-data/v1/index.json'),[q,setQ]=useState(''),[status,setStatus]=useState('');
 const ids=new Set([...workspace.bookmarks,...Object.keys(workspace.plans),...workspace.trips.flatMap(t=>t.destinations.map(d=>d.hut_id))]);
 const rows=useMemo(()=>(data||[]).filter(h=>ids.has(h.id)&&(!q||[h.name,h.id,h.region,h.mountain_group].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!status||(workspace.plans[h.id]?.photos_taken||'Not recorded')===status)),[data,workspace,q,status]);
 const taken=(data||[]).filter(h=>['Taken','Edited','Published'].includes(workspace.plans[h.id]?.photos_taken||'')).length;
 return <><p className="hut-kicker">Private photography life list</p><h1>My huts, plans and photographs</h1><p className="hut-lead">Keep a personal record of the huts you saved or planned, and mark the photographs you have taken. Photo status is your record; it does not establish a hut visit or change the researched facts.</p><div className="hut-private"><p>{workspace.bookmarks.length} saved huts · {workspace.trips.length} hut trips · {taken} huts marked Taken, Edited or Published.</p><p>{user?'Private to your account.':'Saved in this browser. Sign in and explicitly import guest data for cross-device saves.'}</p></div><div className="hut-form"><label>Find in my list<input type="search" value={q} onChange={e=>setQ(e.target.value)}/></label><label>Photo status filter<select aria-label="Photo status filter" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All photo statuses</option>{['Not recorded','Planned','Taken','Edited','Published'].map(s=><option key={s}>{s}</option>)}</select></label></div><div className="hut-actions"><a className="hut-button" href="/huts">Add huts from the library</a><a href="/explore-app/planner/trips">Plan a hut trip</a></div>{error&&<p role="alert">{error}</p>}{!ready&&<p>Checking your private workspace…</p>}<div className="hut-grid">{rows.map(h=><article className="hut-card" key={h.id}><p className="hut-kicker">No. {h.number} · ID {h.id}{workspace.bookmarks.includes(h.id)?' · Saved':''}</p><h2><a href={'/huts/'+h.id}>{h.name}</a></h2><p className="hut-meta">{h.region} · {h.mountain_group}</p><label>My photo status<select aria-label={'Photo status for '+h.name} disabled={!ready} value={workspace.plans[h.id]?.photos_taken||'Not recorded'} onChange={e=>change(w=>{(w.plans[h.id]??={}).photos_taken=e.target.value;})}>{['Not recorded','Planned','Taken','Edited','Published'].map(s=><option key={s}>{s}</option>)}</select></label><p className="hut-meta">My shoot date: {workspace.plans[h.id]?.shoot_date||'Not chosen'}</p><div className="hut-actions"><a href={'/huts/'+h.id+'#section=documentary'}>Open my shoot plan</a></div></article>)}</div>{ready&&data&&!rows.length&&<p className="hut-empty">No huts match your personal list yet. Save a hut, add it to a trip, or import your existing guide export.</p>}<DataTools/></>;
}
