"use client";
import {useEffect,useState,type ReactNode} from 'react';
import {safeUrl,text,type ResearchRow,type HutDetail} from '@/lib/huts/types';
export function useResearch<T>(path:string){const [data,setData]=useState<T|null>(null),[error,setError]=useState('');useEffect(()=>{let live=true;setData(null);setError('');fetch(path,{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('This research page is unavailable. Reconnect or save the hut for offline use.');return r.json();}).then(v=>{if(live)setData(v as T);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[path]);return {data,error};}
export function OutLink({url,children}:{url:unknown;children:ReactNode}){const u=safeUrl(url);return u?<a href={u} target="_blank" rel="noopener noreferrer">{children}</a>:<span>{text(url)}</span>;}
export function Facts({items}:{items:Array<[string,unknown]>}){return <dl className="hut-facts">{items.map(([label,v])=><div key={label}><dt>{label}</dt><dd>{text(v)}</dd></div>)}</dl>;}
export function RefLinks({value,sources}:{value:unknown;sources:ResearchRow[]}){const refs=[...new Set(String(value||'').match(/S\d{5}/g)||[])];if(!refs.length)return <span className="hut-muted">Source not established in checked data</span>;return <span className="hut-muted">{refs.map((ref,i)=>{const source=sources.find(s=>s.ref===ref);return <span key={ref}>{i?' · ':''}<a href={'#source-'+ref} title={String(source?.title||ref)}>{ref}</a></span>;})}</span>;}
export function FullRecord({row,label='Full reviewed record'}:{row:ResearchRow;label?:string}){return <details><summary>{label}</summary><dl>{Object.entries(row).filter(([k])=>!['hut_ids','hut_numbers','base','field_reviews'].includes(k)).map(([k,v])=><div className="hut-row" key={k}><dt><strong>{k.replaceAll('_',' ')}</strong></dt><dd className="hut-prose" style={{margin:'0'}}>{typeof v==='string'&&safeUrl(v)?<OutLink url={v}>{v}</OutLink>:text(v)}</dd></div>)}</dl></details>;}
export function SourceRow({source}:{source:ResearchRow}){return <article id={'source-'+source.ref} className="hut-row"><h3>{String(source.ref)} · {text(source.title)}</h3><p><OutLink url={source.url}>{String(source.url||'Link not established')}</OutLink></p><p className="hut-meta">{text(source.kind)} · {text(source.status)} · Checked {text(source.checked)}</p><p className="hut-prose">{text(source.use)}</p>{Boolean(source.revision)&&<p className="hut-meta">Source revision: {text(source.revision)}</p>}</article>;}
export function RouteRow({row,sources}:{row:ResearchRow;sources:ResearchRow[]}){return <article className="hut-row"><h3>{text(row.destination)}</h3><Facts items={[['Published time',row.time],['Via',row.via],['Grade / terrain',row.grade||row.terrain]]}/><p className="hut-prose">{text(row.details)}</p>{Boolean(row.path)&&<p className="hut-prose">Path: {text(row.path)}</p>}<p className="hut-meta">{text(row.kind)} · Checked {text(row.checked)} · <RefLinks value={row.source_ref||row.ref} sources={sources}/></p><OutLink url={row.sourceURL||row.link}>Official route reference</OutLink><FullRecord row={row}/></article>;}
export function ApproachSelect({detail,value,onChange,label='Published approach'}:{detail:HutDetail;value:string;onChange:(id:string)=>void;label?:string}){const routes=detail.routes.filter(r=>r.kind==='Approach');return <label>{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose a published approach</option>{routes.map(r=><option key={String(r.web_route_id)} value={String(r.web_route_id)}>{String(r.destination)} · {String(r.time||'Time not listed')}{r.via?' · via '+r.via:''}</option>)}</select></label>;}
