"use client";
import {useEffect,useState} from 'react';
import {type Trip,type SharedTrip,type HutIndex} from '@/lib/huts/types';
import release from '@/public/huts-data/v1/manifest.json';
import {shareProjection} from '@/lib/huts/workspace';
import {useWorkspace} from './WorkspaceProvider';
import {useResearch} from './research';
type Link={id:string;name:string;created_at:string;revoked:boolean};
export default function ShareTrip({trip}:{trip:Trip}){
 const {user,pending,sync,online}=useWorkspace(),{data:index}=useResearch<HutIndex[]>('/huts-data/v1/index.json'),[notes,setNotes]=useState(false),[day,setDay]=useState(false),[links,setLinks]=useState<Link[]>([]),[url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[created,setCreated]=useState<SharedTrip|null>(null);
 const view=shareProjection(trip,{notes,day_log:day},release.release);
 async function reload(){const r=await fetch('/api/hut-shares',{cache:'no-store'});if(r.ok)setLinks(((await r.json()) as {shares:Link[]}).shares);}
 useEffect(()=>{if(user)void reload();},[user,trip.id]);
 async function create(){setBusy(true);setError('');try{await sync();const r=await fetch('/api/hut-shares',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip_id:trip.id,notes,day_log:day,expected:Object.fromEntries(Object.entries(view).filter(([key])=>key!=='created_at'))})});const body=await r.json() as {error?:string;url:string;view:SharedTrip};if(!r.ok)throw Error(body.error||'Sharing failed.');setUrl(body.url);setCreated(body.view);await reload();}catch(e){setError(e instanceof Error?e.message:'Sharing failed.');}finally{setBusy(false);}}
 async function revoke(id:string){setError('');try{const r=await fetch('/api/hut-shares?id='+encodeURIComponent(id),{method:'DELETE'});if(!r.ok)throw Error('The share could not be revoked.');await reload();setUrl('');setCreated(null);}catch(e){setError(e instanceof Error?e.message:'Revoke failed.');}}
 return <section className="hut-panel hut-no-print"><h2>Review what friends will see</h2><p>Anyone with the link can read this snapshot until you revoke it. The link contains the trip title, date and selected huts / published approaches. Your documentary plans and permission evidence are excluded.</p><fieldset><legend>Optional fields to include</legend><label><input type="checkbox" checked={notes} onChange={e=>{setNotes(e.target.checked);setUrl('');setCreated(null);}}/> Include these itinerary notes</label><label><input type="checkbox" checked={day} onChange={e=>{setDay(e.target.checked);setUrl('');setCreated(null);}}/> Include this day log and photo status</label></fieldset><div className="hut-private"><h3>Read-only preview</h3><p><strong>{view.name}</strong> · {view.date||'Date not chosen'}</p><ul>{view.destinations.map(d=><li key={d.hut_id}>{index?.find(h=>h.id===d.hut_id)?.name||'Hut ID '+d.hut_id} · {d.approach_id?'Selected published approach included':'Approach not selected'}</li>)}</ul>{notes&&<p className="hut-prose">{view.notes||'Itinerary notes are empty.'}</p>}{day&&<><p>{view.shoot_status}</p><p className="hut-prose">{view.day_notes||'Day log is empty.'}</p></>}</div>{!user&&<p><a href="/account?return=/explore-app/planner/trips">Sign in</a> to create and revoke sharing links.</p>}{user&&<button disabled={busy||pending||!online} onClick={()=>void create()}>{busy?'Creating…':pending?'Save pending — sync before sharing':'Create this read-only link'}</button>}{url&&<><p>Link created from the reviewed saved trip. Later private edits do not update this snapshot.</p><label>Read-only trip URL<input readOnly value={url} onFocus={e=>e.target.select()}/></label><div className="hut-actions"><a href={url} target="_blank" rel="noopener noreferrer">Open shared preview</a><button onClick={()=>void navigator.clipboard.writeText(url).catch(()=>setError('Select and copy the URL above.'))}>Copy sharing link</button></div>{created&&<details><summary>Exact shared fields</summary><pre>{JSON.stringify(created,null,2)}</pre></details>}</>}{error&&<p className="hut-alert" role="alert">{error}</p>}{user&&<details><summary>My sharing links</summary><p className="hut-muted">URLs are shown when created. If you lose one, create a new link and revoke the old one.</p>{links.length?links.map(l=><div className="hut-row" key={l.id}><p>{l.name} · Created {l.created_at} · {l.revoked?'Revoked':'Active'}</p>{!l.revoked&&<button className="hut-small" onClick={()=>void revoke(l.id)}>Revoke link</button>}</div>):<p>No links created.</p>}</details>}</section>;
}
