"use client";
import {type SharedTrip,type HutDetail,text} from '@/lib/huts/types';
import {useResearch,Facts,OutLink} from './research';
function SharedHut({id,approach}:{id:string;approach:string}){const {data,error}=useResearch<HutDetail>('/huts-data/v1/'+id+'.json');if(error)return <p>{error}</p>;if(!data)return <p>Loading hut…</p>;const route=data.routes.find(r=>r.web_route_id===approach);return <article className="hut-panel"><p className="hut-kicker">No. {data.record.number} · ID {id}</p><h2><a href={'/huts/'+id}>{data.record.name}</a></h2><p className="hut-notice">{text(data.record.notice_summary||data.record.review_flags)} · Checked {text(data.record.notice_checked||data.record.checked)}</p><Facts items={[['Selected published approach',route?text(route.destination):'Not selected'],['Published walking time',route?.time],['Via',route?.via]]}/>{route&&<OutLink url={route.sourceURL||route.link}>Approach source</OutLink>}<p className="hut-muted">Confirm current conditions with the operator. This is a published reference, not turn-by-turn navigation.</p></article>;}
export default function SharedTripPage({token}:{token:string}){
 const {data,error}=useResearch<{view:SharedTrip}>('/api/hut-shares/'+encodeURIComponent(token));
 if(error)return <><h1>This trip link is unavailable</h1><p>The owner may have revoked it, or the service is unavailable. Ask the owner for a current link.</p><a href="/huts">Browse the public hut library</a></>;
 if(!data)return <p>Opening read-only trip…</p>;const t=data.view;
 return <><p className="hut-kicker">Shared trip · Read only</p><h1>{t.name}</h1><p className="hut-lead">{t.date||'Date not chosen'}</p><p className="hut-meta">Snapshot created {t.created_at} · Research release {t.release}. Later edits to the private trip do not update this snapshot.</p><div className="hut-columns">{t.destinations.map(d=><SharedHut key={d.hut_id} id={d.hut_id} approach={d.approach_id}/>)}</div>{t.notes!==undefined&&<section className="hut-section"><h2>Shared itinerary notes</h2><p className="hut-prose">{t.notes||'No itinerary notes.'}</p></section>}{t.day_notes!==undefined&&<section className="hut-section"><h2>Shared day log</h2><p>{t.shoot_status}</p><p className="hut-prose">{t.day_notes||'No day log.'}</p></section>}<p className="hut-muted">Personal notes above were selected by the trip owner. They are separate from the reviewed public hut research.</p><div className="hut-actions"><a className="hut-button" href="/huts">Browse all 630 huts</a><button className="secondary" onClick={()=>window.print()}>Print shared trip</button></div></>;
}
