"use client";
import {useState} from 'react';
import {type HutDetail,type ShootField,text} from '@/lib/huts/types';
import fields from '@/lib/huts/generated/shoot-fields.json';
import {solarTimes} from '@/lib/huts/solar-planning.cjs';
import {useWorkspace} from './WorkspaceProvider';
import {Facts,FullRecord,ApproachSelect} from './research';
const groups=[{label:'Still photography and light',keys:['shoot_date','viewpoint','focal_length','photos_taken','hut_orientation','morning_spot','evening_spot']},{label:'Time-lapse and seasons',keys:['sky_exposure','night_sky','seasonal_change']},{label:'Drone review and proposals',keys:['drone_permission','drone_review_date','no_fly_zones','drone_evidence','aerial_angles']},{label:'Archival rights and filming consent',keys:['archival_rights','archival_sources','interview_permission','consent_notes','personal_notes']}];
export default function ShootPlan({detail}:{detail:HutDetail}){
 const {workspace,change,user}=useWorkspace(),h=detail.record,plan=workspace.plans[h.id]||{},[approach,setApproach]=useState('');
 const time=solarTimes(plan.shoot_date||'',typeof h.latitude==="number"?h.latitude:NaN,typeof h.longitude==="number"?h.longitude:NaN);
 const route=detail.routes.find(r=>r.web_route_id===approach);
 function printPrivate(){const app=document.querySelector('.hut-app')!;app.classList.add('hut-print-private');window.addEventListener('afterprint',()=>app.classList.remove('hut-print-private'),{once:true});window.print();}
 function update(field:ShootField,value:string){change(w=>{(w.plans[h.id]??={})[field.key]=value;});}
 return <><div className="hut-private"><h3>My documentary plan</h3><p>{user?'Private to your account.':'Saved in this browser. Sign in and import the guest workspace to save across devices.'} These are scouting notes and personal permission records.</p><button className="secondary" onClick={printPrivate}>Print my private shoot plan</button></div>
 {groups.map(group=><fieldset key={group.label} className="hut-section"><legend>{group.label}</legend>{group.label.startsWith('Drone')&&<p className="hut-muted">Check current official airspace, protected-area and landowner requirements before every flight. A recorded permission applies only within its scope and dates. Proposed angles do not grant permission.</p>}<div className="hut-form">{group.keys.map(key=>{const field=(fields as ShootField[]).find(f=>f.key===key);if(!field)return null;const value=plan[key]??field.default??'';return <label key={key} className={field.type==='textarea'?'wide':''}>{field.label}{field.type==='select'?<select aria-label={field.label} value={value} onChange={e=>update(field,e.target.value)}>{field.options?.map(v=><option key={v}>{v}</option>)}</select>:field.type==='textarea'?<textarea aria-label={field.label} value={value} maxLength={3000} onChange={e=>update(field,e.target.value)}/>:<input aria-label={field.label} type={field.type==='date'?'date':field.type==='number'?'number':'text'} min={field.type==='number'?1:undefined} max={field.type==='number'?2000:undefined} value={value} maxLength={3000} onChange={e=>update(field,e.target.value)}/>}<span className="hut-print-only">{value||"Not recorded"}</span></label>;})}</div></fieldset>)}
 <div className="hut-panel"><h3>Light and approach timing</h3>{time?<><Facts items={[['Sunrise · '+time.zone,time.sunrise],['Sunset',time.sunset],['Morning golden window',time.goldenMorning],['Evening golden window',time.goldenEvening],['Morning blue window',time.blueMorning],['Evening blue window',time.blueEvening],['Sunrise bearing',time.sunriseAzimuth===null?'Not available':time.sunriseAzimuth+'° from north'],['Sunset bearing',time.sunsetAzimuth===null?'Not available':time.sunsetAzimuth+'° from north']]}/><p className="hut-muted">{time.qualification} SunCalc 1.9.0.</p></>:<p>Choose a valid shoot date above to calculate the astronomical light windows. A known latitude and longitude are required.</p>}<ApproachSelect detail={detail} value={approach} onChange={setApproach} label="Compare a published approach time"/>{route&&<p>{text(route.destination)} · published time {text(route.time)} · via {text(route.via)}. Allow for your pace, conditions and photography stops; this is not a computed navigation route.</p>}</div>
 <details><summary>Documentary formats and researched story hooks</summary>{detail.film_formats.map((f,i)=><FullRecord key={i} row={f} label={String(f.title||f.format||f.name||'Film format')}/>)}</details></>;
}
