"use client";
import {useEffect,useState} from 'react';
import {text,type Trip,type HutDetail,type HutIndex} from '@/lib/huts/types';
import {useWorkspace} from './WorkspaceProvider';
import {useResearch,ApproachSelect,RefLinks,Facts,OutLink} from './research';
import DataTools from './DataTools';
import ShareTrip from './ShareTrip';
import {solarTimes} from '@/lib/huts/solar-planning.cjs';
const checks=[['access','Current operation, access and winter-room restrictions checked'],['weather','Weather, daylight and mountain conditions checked'],['travel','Valley travel, last return connection and parking rules checked'],['beds','Reservation, bedding, dietary request and payment checked'],['offline','Hut guide and required route information saved offline'],['permissions','Filming consent, archival rights and any flight checks reviewed']];
function Destination({trip,id,today}:{trip:Trip;id:string;today:boolean}){
 const {data,error}=useResearch<HutDetail>('/huts-data/v1/'+id+'.json'),{change}=useWorkspace();
 if(error)return <p role="alert">{error}</p>;if(!data)return <p>Loading hut…</p>;
 const h=data.record,dest=trip.destinations.find(d=>d.hut_id===id)!,route=data.routes.find(r=>r.web_route_id===dest.approach_id);
 const light=solarTimes(trip.date,typeof h.latitude==='number'?h.latitude:NaN,typeof h.longitude==='number'?h.longitude:NaN);
 return <article className="hut-panel"><p className="hut-kicker">No. {h.number} · ID {id}</p><h2><a href={'/huts/'+id}>{h.name}</a></h2><p className={String(h.review_flags).startsWith('No specific')?'hut-muted':'hut-notice'}>{text(h.notice_summary||h.review_flags)} · Checked {text(h.notice_checked||h.checked)}</p><Facts items={[['Service / season',h.summer],['Valley starting point',h.car],['Parking',h.parking],['Winter access',h.winter_notes||h.winter_room]]}/>{today?<><h3>Selected published approach</h3><p>{route?text(route.destination)+' · '+text(route.time)+' · via '+text(route.via):'Choose a published approach in the trip plan.'}</p>{route&&<p className="hut-meta">Checked {text(route.checked)} · <RefLinks value={route.source_ref} sources={data.sources}/> · <OutLink url={route.sourceURL||route.link}>Route source</OutLink></p>}</>:<ApproachSelect detail={data} value={dest.approach_id} onChange={value=>change(w=>{const d=w.trips.find(t=>t.id===trip.id)?.destinations.find(d=>d.hut_id===id);if(d)d.approach_id=value;})}/>}
 <p className="hut-muted">Published walking time is a reference. Allow for pace, conditions and photography stops. No valley driving time is inferred.</p>{light&&<><Facts items={[['Sunrise · '+light.zone,light.sunrise],['Sunset',light.sunset],['Morning golden / blue',light.goldenMorning+' / '+light.blueMorning],['Evening golden / blue',light.goldenEvening+' / '+light.blueEvening]]}/><p className="hut-muted">{light.qualification}</p></>}<div className="hut-actions"><a href={'/huts/'+id+'#section=documentary'}>Open private shoot plan</a><a href={'/huts/'+id}>Review / save hut guide</a>{!today&&<button className="hut-small" onClick={()=>change(w=>{const t=w.trips.find(t=>t.id===trip.id);if(t)t.destinations=t.destinations.filter(d=>d.hut_id!==id);})}>Remove from trip</button>}</div></article>;
}
export default function TripWorkspace({today=false}:{today?:boolean}){
 const {workspace,user,change,ready}=useWorkspace(),{data:index}=useResearch<HutIndex[]>('/huts-data/v1/index.json');
 const [selected,setSelected]=useState(''),[newName,setNewName]=useState(''),[newDate,setNewDate]=useState(''),[hut,setHut]=useState(''),[find,setFind]=useState(''),[showShare,setShowShare]=useState(false);
 useEffect(()=>{const p=new URLSearchParams(location.search);setSelected(p.get('trip')||'');},[]);
 const trip=workspace.trips.find(t=>t.id===selected)||workspace.trips[0];
 function select(id:string){setSelected(id);history.replaceState(null,'',location.pathname+'?trip='+encodeURIComponent(id));setShowShare(false);}
 function update(fn:(t:Trip)=>void){if(!trip)return;change(w=>{const t=w.trips.find(t=>t.id===trip.id);if(t)fn(t);});}
 function create(){const id=crypto.randomUUID();change(w=>w.trips.push({id,name:newName.trim()||'New hut trip',date:newDate,destinations:[],notes:'',checklist:{},shoot_status:'Planned',day_notes:''}));setNewName('');setNewDate('');select(id);}
 return <><p className="hut-kicker">{today?'Field day':'Private trip workspace'}</p><h1>{today?'Today at the hut':'My hut trips'}</h1><p className="hut-lead">{today?'Keep the selected approach, light windows and final checks within reach. Record what happened after the shoot.':'Plan around published approaches, access notices and your shoot date. Create a trip, choose huts, then review the details before leaving Vienna.'}</p>{!user&&<p className="hut-private">This guest workspace is saved in this browser. <a href="/account?return=/explore-app/planner/trips">Sign in</a> for cross-device saves, then explicitly import any guest data you want in your account.</p>}
 {!today&&<section className="hut-panel hut-no-print"><h2>Create a hut trip</h2><div className="hut-form"><label>New trip name<input value={newName} maxLength={120} onChange={e=>setNewName(e.target.value)} placeholder="Rax weekend — one hut, one story"/></label><label>Visit / shoot date<input type="date" value={newDate} onChange={e=>setNewDate(e.target.value)}/></label></div><div className="hut-actions"><button disabled={!ready} onClick={create}>Create trip</button><a href="/huts">Choose huts in the library</a></div></section>}
 {workspace.trips.length>0&&<label className="hut-no-print">Choose a trip<select aria-label="Choose a trip" value={trip?.id||''} onChange={e=>select(e.target.value)}>{workspace.trips.map(t=><option value={t.id} key={t.id}>{t.name}{t.date?' · '+t.date:''}</option>)}</select></label>}
 {trip?<><section className="hut-section"><div className="hut-form">{today?<><h2>{trip.name}</h2><p>{trip.date||'Date not chosen'}</p></>:<><label>Trip name<input value={trip.name} maxLength={120} onChange={e=>update(t=>{t.name=e.target.value;})}/></label><label>Shoot date<input type="date" value={trip.date} onChange={e=>update(t=>{t.date=e.target.value;})}/></label><label className="wide">Private itinerary notes<textarea className="hut-screen-only" aria-label="Private itinerary notes" value={trip.notes} maxLength={3000} onChange={e=>update(t=>{t.notes=e.target.value;})}/><span className="hut-print-only">{trip.notes||"No itinerary notes recorded."}</span></label></>}</div><div className="hut-actions"><a className="hut-button" href={(today?'/explore-app/planner/trips':'/explore-app/planner/today')+'?trip='+trip.id}>{today?'Edit this trip':'Open Field day'}</a><button className="secondary" onClick={()=>setShowShare(s=>!s)}>Share a read-only trip</button><button className="secondary" onClick={()=>window.print()}>Print trip</button></div>{showShare&&<ShareTrip trip={trip}/>}</section>
 {!today&&<section className="hut-panel hut-no-print"><h3>Add a hut</h3><div className="hut-form"><label>Find by name or ID<input type="search" value={find} onChange={e=>setFind(e.target.value)}/></label><label>Choose hut<select aria-label="Choose hut" value={hut} onChange={e=>setHut(e.target.value)}><option value="">Choose a hut</option>{(index||[]).filter(h=>!trip.destinations.some(d=>d.hut_id===h.id)&&(!find||[h.name,h.id,h.mountain_group].join(' ').toLowerCase().includes(find.toLowerCase()))).map(h=><option key={h.id} value={h.id}>{h.name} · No. {h.number} · ID {h.id}</option>)}</select></label></div><button disabled={!hut||trip.destinations.length>=30} onClick={()=>{update(t=>{if(!t.destinations.some(d=>d.hut_id===hut))t.destinations.push({hut_id:hut,approach_id:''});});setHut('');}}>Add selected hut</button></section>}
 <section className="hut-section"><h2>{today?'Huts and timing':'Selected huts and published approaches'}</h2><div className="hut-columns">{trip.destinations.map(d=><Destination key={d.hut_id} trip={trip} id={d.hut_id} today={today}/>)}</div>{!trip.destinations.length&&<p className="hut-empty">No huts in this trip yet. Choose one above or add a hut from its library page.</p>}</section>
 <section className="hut-panel hut-section"><h2>Before leaving</h2><p>Mark each reminder after checking it. A tick records your review; it does not establish access, availability or legal permission.</p><fieldset><legend>My trip checks</legend>{checks.map(([key,label])=><label key={key}><input type="checkbox" checked={trip.checklist[key]||false} onChange={e=>update(t=>{t.checklist[key]=e.target.checked;})}/>{label}</label>)}</fieldset></section>
 <section className="hut-private hut-section"><h2>My day log</h2><div className="hut-form"><label>Photo status<select aria-label="Photo status" value={trip.shoot_status} onChange={e=>update(t=>{t.shoot_status=e.target.value;})}>{['Not logged','Planned','Photos taken','No photos today'].map(s=><option key={s}>{s}</option>)}</select></label><label className="wide">What happened / expenses / follow-up<textarea className="hut-screen-only" aria-label="What happened / expenses / follow-up" maxLength={3000} value={trip.day_notes} onChange={e=>update(t=>{t.day_notes=e.target.value;})}/><span className="hut-print-only">{trip.day_notes||"No day log recorded."}</span></label></div><p className="hut-muted">These are personal records. They do not update the reviewed public hut facts.</p></section></>:<p className="hut-empty">{today?'Create a hut trip before opening Field day.':'No hut trips yet. Your saved huts and imported documentary plans are available in the library.'}</p>}
 <DataTools/><div className="hut-actions"><a href="/explore-app/planner/list">My photography life list</a><a href="/huts?saved=1">My saved huts</a><a href="/huts">Browse all 630 huts</a><a href="/explore-app/planner">Climbing calendar and existing planner</a></div></>;
}
