PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS hut_user(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,email_verified INTEGER NOT NULL DEFAULT 0,image TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS hut_session(id TEXT PRIMARY KEY,expires_at INTEGER NOT NULL,token TEXT NOT NULL UNIQUE,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,ip_address TEXT,user_agent TEXT,user_id TEXT NOT NULL REFERENCES hut_user(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS hut_session_user ON hut_session(user_id);
CREATE TABLE IF NOT EXISTS hut_account(id TEXT PRIMARY KEY,account_id TEXT NOT NULL,provider_id TEXT NOT NULL,user_id TEXT NOT NULL REFERENCES hut_user(id) ON DELETE CASCADE,access_token TEXT,refresh_token TEXT,id_token TEXT,access_token_expires_at INTEGER,refresh_token_expires_at INTEGER,scope TEXT,password TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS hut_account_user ON hut_account(user_id);
CREATE TABLE IF NOT EXISTS hut_verification(id TEXT PRIMARY KEY,identifier TEXT NOT NULL,value TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER,updated_at INTEGER);
CREATE TABLE IF NOT EXISTS hut_rate_limit(id TEXT PRIMARY KEY,key TEXT NOT NULL UNIQUE,count INTEGER NOT NULL,last_request INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS hut_workspace(user_id TEXT PRIMARY KEY REFERENCES hut_user(id) ON DELETE CASCADE,payload TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 0,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS hut_share(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES hut_user(id) ON DELETE CASCADE,trip_id TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,payload TEXT NOT NULL,created_at TEXT NOT NULL,revoked INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS hut_share_owner ON hut_share(user_id);
